version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
    ports:
        - "5432:5432"

  api:
    container_name:  "api"
    # we want to use the image which is build from our Dockerfile
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      DB_USER: postgres
      DB_PASS: 123456
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: golang_api
      JWT_SECRET: ashpex
    depends_on:
      - db
    networks:
      - default
    volumes:
      - .:/app/

